<head>
<style>
hr { 
  display: block;
  margin-top: 1em;
  margin-bottom: 0.5em;
  margin-left: auto;
  margin-right: auto;
  border-style: inset;
  border-width: 10px;
} 
    
ul {
border: solid 1px green;
width:800px;
margin:0 auto;
padding: 0;
}
li {
display:inline;
list-style-type:none;
}
div {
border: solid 1px red;
width:900px;
height:50px;
text-align:center;
}

</style>
</head>
<h1><center>IT-TOOLS FOR PHYSICIST 2.0</center></h1>
<h3><center> Authors: Wahid Redjeb, Giacomo Boldrini</center></h3>
 <hr width = "50%">  
<h2><center>Machine Learning</center></h2>
<h3><center> Regression and Classification using Keras and Tensorflow</center></h3>


<body >
        In the last lectures we studied the meaning of <b>Machine Learning</b> and in particular we saw what an <b>Artificial Neural Network</b> is, how to implement it and how to exploit it.
            In this lecture we will see how to build <b>models</b> which permit us to perform Linear Regression and Classifications.
   </body>
   
The notebook divided in two sections:<br>
    <ul>
        <li><a href='#Keras'>Keras</a></li>     
        <li><a href=#section2>Tensorflow</a></li>
    </ul>


<h1><center>Keras</center></h1>
<hr width = '1%'><br>
<img src ='./images/keras-logo-2018-large-1200.png'>

<body>
     <i>Keras</i> is an open source library written in Python for Machine Learning purposes. In particular Keras is an high level <b>API</b> for neural networks (Application Programming Interface) which works on Tensorflow.
        This library was developed focusing on the possibility to perform "experiment" in a fast way.</br>
        <ul>
            <li>Keras permits an easy and fast prototipation of the algorithms.</li>
            <li>It supports both Convolutional NN and Recurrent NN, and moreover it permits them combination.</li>
       <li>An important feature of Keras is that with it we don't have to worry on which computation tool you are working on, Keras is written in a such way that it can be compiled on CPU or GPU.</li>
        </ul>
    

More info about Keras: <a href="https://keras.io/"> KERAS </a>

</body>



In [1]:
!pip install keras

In [2]:
import keras
print("Keras version:", keras.__version__)

Using TensorFlow backend.


Keras version: 2.2.4


<a id='section2'></a>
<h1><center> Tensorflow</center></h1>
<hr width = '50%'>
<img src ='./images/logo-color-tensorflow.png'>


Tensorflow is a free and open-source software library for dataflow and differentiable programming across a range of tasks. It is a symbolic math library, and it is also used for machine learning applications such as neural network.
It has a flexible architecture which allows an easy deplyment of computation across a variety of platform (CPUs,GPUs,TPUs), and from desktops to cluster off servers to mobile and edge devices.
It was originally developed by researchers and engineers from the Google Brain team within Google's AI organization.
More info about TF: <a href="https://www.tensorflow.org/"> TensorFlow </a>

In [3]:
!pip install tensorflow==1.15.0

In [4]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.metrics import accuracy_score

print("Tensorflow version:",(tf.__version__))

Tensorflow version: 1.15.0


When experimenting with TensorFlow interactively, it's convenient to use <code>tf.InteractiveSession()</code>. Invoking this statement within IPython (an interactive Python Shell) will make TensorFlow behave almost imperatively, allowing beginners to play with tensors much mor easily. You will learn about imperative versus declarative style in greater depth later.

In [5]:
tf.InteractiveSession()

<h3> Initializing Constant Tensors </h3>

In [6]:
tf.zeros(2) #it takes the shape of the tensor, [dim1,....,dimn]


<tf.Tensor 'zeros:0' shape=(2,) dtype=float32>

Note that TF returns a reference to thedesired tensor rather than the value of the tensor itself. To force the value of the tensor ro be returned, we will use the method <code>eval()</code> of the tensor object.

In [7]:
a = tf.zeros(2)
eval = a.eval()
print("The type returned by the method eval() is: ",(type(a.eval())))

The type returned by the method eval() is:  <class 'numpy.ndarray'>


What if we'd like a tensor filled with some quantity besides 1/0? 

In [8]:
tensor = tf.fill((2,2), value = 5.)
tensor.eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

There is a similar method, <code>constant()</code> which allows the construction of tensors that shouldn't change during the program execution.

In [9]:
const_tensor = tf.constant(3., shape = (10,2))
const_tensor.eval()

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]], dtype=float32)

<h3>Samping Random Tensors </h3>

In [10]:
#Someone can pass as argument the seed in order to have the same sampling
normal_tensor = tf.random_normal((2,2), mean = 0, stddev=1, seed = 42)
normal_tensor.eval()


array([[-0.28077507, -0.1377521 ],
       [-0.6763296 ,  0.02458041]], dtype=float32)

One thing to note is that machine learning systems often make use of very large ten‐
sors that often have tens of millions of parameters. When we sample tens of millions
of random values from the Normal distribution, it becomes almost certain that some
sampled values will be far from the mean. Such large samples can lead to numerical
instability, so it’s common to sample using <code>tf.truncated_normal()</code> instead of <code>tf.ran
dom_normal()</code>. This function behaves the same as <code>tf.random_normal()</code> in terms of
API, but drops and resamples all values more than two standard deviations from the
mean.


In [11]:
norm_trunc_tensor = tf.truncated_normal((10,3), mean = 0, stddev = 1, seed = 42)
norm_trunc_tensor.eval()

array([[-0.28077507, -0.1377521 , -0.6763296 ],
       [ 0.02458041, -0.46845472, -0.00246632],
       [-0.9745911 ,  0.6638492 ,  0.4368011 ],
       [-0.7038976 ,  0.6426843 ,  1.4513893 ],
       [ 1.8412819 , -0.15879929, -1.0607921 ],
       [ 1.5984018 , -0.11424706,  1.4045748 ],
       [-0.05878579, -0.42446467, -0.37023765],
       [-0.5268839 , -0.31035113, -0.59968674],
       [-0.01448264,  1.9438368 , -0.5893153 ],
       [ 1.15643   ,  1.0532719 ,  0.52549994]], dtype=float32)

In [12]:
#Sampling a tensor with a uniformly random entries in a fixed interval
uniform_tensor = tf.random_uniform((2,2), minval = -2, maxval = 2)
uniform_tensor.eval()

array([[-1.4059453 , -0.59825754],
       [-1.8191795 , -0.3599682 ]], dtype=float32)

In [13]:
#Adding tensors together
c = tf.ones((2,2)) #return float32
d = tf.fill((2,2), value = 5.)
sum_tensor = c + d
sum_tensor.eval()


array([[6., 6.],
       [6., 6.]], dtype=float32)

Pay attention with the type of tensor you are building

In [14]:
print("tf.ones(): ",(c))
d = tf.fill((2,2), value = 5.)
#or
new_d = tf.to_float(d)
print("tf.fill()", (d))
try_sum = c + d
new_try_sum = c + new_d
new_try_sum.eval()

W1210 19:37:47.630657 139648977106752 deprecation.py:323] From <ipython-input-14-e9a8cfa2abb1>:4: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.


tf.ones():  Tensor("ones:0", shape=(2, 2), dtype=float32)
tf.fill() Tensor("Fill_2:0", shape=(2, 2), dtype=float32)


array([[6., 6.],
       [6., 6.]], dtype=float32)

In [15]:
#Scaling a tensor

c = tf.fill((2,2), value = 2.)
d = tf.fill((2,2,), value = 7.)
scale_tensor = c * d
scale_tensor.eval()

array([[14., 14.],
       [14., 14.]], dtype=float32)

<h3>Matrix operation </h3>

In [16]:
#Creating the identity matrix
identity = tf.eye(4)
identity.eval()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [17]:
#Creating general diagonal matrix

diag = tf.range(1,10,1.) #Creates 1-D tensor
print("Diagonal:",(diag.eval()))

d_tensor = tf.diag(diag)
d_tensor.eval()

Diagonal: [1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 9.]], dtype=float32)

In [18]:
#Transposing a matrix

matrix = tf.ones((4,2))
print("Matrix:\n",(matrix.eval()))

transp_matrix = tf.matrix_transpose(matrix)
print("Transposed Matrix:\n",(transp_matrix.eval()))

Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Transposed Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<h4>Matrix multiplication </h4>

In [19]:
a = tf.fill((2,3), value = 5.)
b = tf.fill((3,2), value = 6.)
print("a:\n {} \nb:\n {}".format(a.eval(),b.eval()))

c = tf.matmul(a,b)
c.eval()

a:
 [[5. 5. 5.]
 [5. 5. 5.]] 
b:
 [[6. 6.]
 [6. 6.]
 [6. 6.]]


array([[90., 90.],
       [90., 90.]], dtype=float32)

<h4> Tensor shape manipulation </h4>

In [20]:
a = tf.ones(10)
print("a:\n",(a.eval()))
print("a shape:\n",(a.get_shape()))

b = tf.reshape(a,(5,2))

print("b:\n",(b.eval()))
print("b shape:\n",(b.get_shape()))

a:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
a shape:
 (10,)
b:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
b shape:
 (5, 2)


Notice how we can turn the original rank-1 tensor into a rank-2 tensor and then into
a rank-3 tensor with tf.reshape. While all necessary shape manipulations can be
performed with <code>tf.reshape()</code>, sometimes it can be convenient to perform simpler
shape manipulations using functions such as <code>tf.expand_dims</code> or <code>tf.squeeze</code>.
tf.expand_dims adds an extra dimension to a tensor of size 1. It’s useful for increas‐
ing the rank of a tensor by one (for example, when converting a rank-1 vector into a
rank-2 row vector or column vector). <code>tf.squeeze</code>, on the other hand, removes all
dimensions of size 1 from a tensor. It’s a useful way to convert a row or column vector
into a flat vector.


In [21]:
a = tf.ones(2)
print("a shape:",(a.get_shape()))
print("a:",(a.eval()))
b = tf.expand_dims(a,0) #Expand first dimension
print("b shape:",(b.get_shape()))
print("b:",(b.eval()))
print("Do you notice the difference?")

a shape: (2,)
a: [1. 1.]
b shape: (1, 2)
b: [[1. 1.]]
Do you notice the difference?


In [22]:
a = tf.ones(2)
print("a shape:",(a.get_shape()))
print("a:\n",(a.eval()))
b = tf.expand_dims(a,1) #Expand first dimension
print("b shape:",(b.get_shape()))
print("b:\n",(b.eval()))
print("Do you notice the difference?")

a shape: (2,)
a:
 [1. 1.]
b shape: (2, 1)
b:
 [[1.]
 [1.]]
Do you notice the difference?


In [23]:
d = tf.squeeze(b) #Expand first dimension
print("b shape:",(b.get_shape()))
print("b:\n",(b.eval()))
print("d shape:",(d.get_shape()))
print("d:\n",(d.eval()))


b shape: (2, 1)
b:
 [[1.]
 [1.]]
d shape: (2,)
d:
 [1. 1.]


<h4>Broadcasting </h4>

In [24]:
a = tf.ones((2,2))
print("a:\n",(a.eval()))

b = tf.range(0,2,1, dtype = tf.float32)
print("b:\n",(b.eval()))

print("a shape: {}, b shape: {}".format(a.get_shape(), b.get_shape()))

#Tensorflow permits to add array with different shape (Broadcasting --> Numpy)

c = a + b 
c.eval()



a:
 [[1. 1.]
 [1. 1.]]
b:
 [0. 1.]
a shape: (2, 2), b shape: (2,)


array([[1., 2.],
       [1., 2.]], dtype=float32)

As it can be seen the vector b is added to every row of the matrix a.
Notice: remember to define the tensor with the correct type.

##### TensorFlow session

In TensorFlow, a <code>tf.Session()</code> object stores the context under which a computation
is performed. At the beginning of this chapter, we used <code>tf.InteractiveSession()</code> to
set up an environment for all TensorFlow computations. This call created a hidden
global context for all computations performed. We then used <code>tf.Tensor.eval()</code> to execute our declaratively specified computations. Underneath the hood, this call is
evaluated in context of this hidden global tf.Session. It can be convenient (and
often necessary) to use an explicit context for a computation instead of a hidden context.



In [25]:
sess = tf.Session()

a = tf.ones((2,2))
b = tf.matmul(a,a)

b.eval(session = sess )

array([[2., 2.],
       [2., 2.]], dtype=float32)

The tensor b is evaluated in the context of the session "sess". The same operation che be done using the method <code>run()</code>.

In [26]:
sess.run(b)

array([[2., 2.],
       [2., 2.]], dtype=float32)

##### Tensorflow variables

So far we used constant tensors. While we could combine and recombine these tensors in any way we chose, we could never change the value of tensors themselves (only create new tensors with new values).
The style of programming so far has been <i>functional</i> and not <i>stateful</i>. While functional computations are very useful, machine learning often depens heavily on stateful computations. Learning algorithms are essentially rules for updating stored tensors to explain provided data. If it is not possible to update these stored tensors, it would be hard to learn. 
The <code>tf.Variable()</code> class provides a wrapper around tensors that allows for stateful computations. The variables objects serve as holders for tensors.


In [27]:
var_tensor = tf.Variable(tf.ones((3,3)))

print("Variable tensor: ",(var_tensor))

#var_tensor.eval() Try to evaluate this tensor

Variable tensor:  <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32_ref>


The evaluation fails since variables have to be explicitly initialized. 

In [28]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())
var_tensor.eval(session = sess)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

###### Assigning values to variables

In [29]:
sess.run(var_tensor.assign(tf.fill((3,3),value = 3.)))

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

What would happen if we tried to assign a value to variable <b>var_tensor</b> of not of shape (3,3)? 

In [30]:
#sess.run(var_tensor.assign(tf.fill((2,2),value = 3.)))

The shape of the variable is fixed upon initilization and must be preserved with updates.